# Main database configuration for I-Tee
database:
  adapter: "mysql2"
  host: "mysql.local"
  username: "itee"
  password: "itee"
  database: "itee"

# Database configuration used by I-Tee to manipulate Guacamole users and connections
guacamole_database:
  adapter: "mysql2"
  host: "mysql.local"
  username: "guacamole"
  password: "guacamole"
  database: "guacamole"

# Guacamole specific configuration
# Theoretically I-Tee is able to "mostly" survive without Guacamole but it's not extensively tested.
guacamole:
  # URL prefix to Guacamole API
  url_prefix: "https://i-tee-test.local/guacamole"
  # RDP host used by Guacamole server to connect to I-Tee virtual machines
  rdp_host: "itee.local"

ldap:
  host: "ldap.local"
  port: 389
  ssl: false

  # Bind user and password
  user: "cn=bind-user,dc=local"
  password: "bind-user"

  # Attribute used to indentify users by username
  attribute: "uid"
  base: "ou=users,dc=local"

  # (never really understood what this is for)
  group_base: "ou=groups,dc=local"

# List of fixed usernames of admins/managers
admins: [ ]
managers: [ ]

# Layout theme
skin: "EIK"

# Hostname used to connect to virtual machines via RDP (shown to user)
rdp_host: "i-tee-test.local"

# Development mode (defaults to false). Development mode
# enables class reloading, debug log and developer
# friendlier errors in HTTP responses.
development: true
