{
  "_comment": "Please keep this file JSON compatilble",

  "database": {
    "adapter": "mysql2",
    "host": "mysql.local",
    "username": "itee",
    "password": "itee",
    "database": "itee"
  },

  "guacamole_database": {
    "adapter": "mysql2",
    "host": "mysql.local",
    "username": "guacamole",
    "password": "guacamole",
    "database": "guacamole"
  },

  "guacamole": {
    "host": "https://guacamole.local/guacamole",
   },

  "ldap": {
    "host": "ldap.local",
    "port": 389,
    "attribute": "uid",
    "base": "ou=users,dc=local",
    "group_base": "ou=groups,dc=local",
    "ssl": false,
    "user": "cn=admin,dc=local",
    "password": "password"
  },

  "admins": [ "test_admin" ],

  "managers": [ "test_manager" ],

  "skin": "EIK",
  "rdp_host": "localhost",

  "debug": true
}
