
#mysql:
#  username: itee
#  password: itee
#  database: itee

ldap:
#  host: ldap.local
  host: 172.17.0.1
  port: 389
  attribute: uid
  base: ou=users,dc=local
  group_base: ou=groups,dc=local
  ssl: false
  admin_user: cn=admin,dc=local
  admin_password: Passw0rd

admins:
  - test_admin
  - test_user

managers:
  - test_manager

skin: EIK
rdp_host: elab.itcollege.ee

